# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Code & Stuff'
tagline:             ''
description:         'Hacking and programming<br>Written by <a href="https://github.com/nsarno">@nsarno</a><br>(づ｡◕‿‿◕｡)づ'
url:                 'http://nsarno.github.io'
baseurl:             /
paginate:            2

# About/contact
author:
  name:              Arnaud Mesureur
  url:               https://twitter.com/nsarnaud
  email:             arnaud.mesureur@gmail.com

# Custom vars
version:             1.0.0
