# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Code & Stuff'
tagline:             ''
description:         'Programming &<br> Programming &<br> Programming &<br> ...<br> Written by <a href="https://twitter.com/nsarnaud">@nsarnaud</a><br>(づ｡◕‿‿◕｡)づ'
url:                 http://nsarno.github.io
baseurl:             /
paginate:            1

# About/contact
author:
  name:              Arnaud Mesureur
  url:               https://twitter.com/nsarnaud
  email:             arnaud.mesureur@gmail.com

# Custom vars
version:             1.0.0
